export const uiTranslations = {
  // Formatting and UI elements
  characters: 'characters',
  words: 'words',
  tips: 'Writing Tips',
  tipClear: 'Be clear and concise',
  tipRespectful: 'Maintain a respectful tone',
  tipFacts: 'Focus on facts and evidence',
  tipSpecific: 'Be specific about your case',
  tipProofread: 'Proofread before submitting',
  hideDetails: 'Hide Tips',
  showDetails: 'Show Tips',
  formatBold: 'Bold',
  formatItalic: 'Italic',
  formatUnderline: 'Underline',
  formatUppercase: 'UPPERCASE',
  formatLowercase: 'lowercase',

  // Help Assistant
  helpAssistant: 'Help Assistant',
  helpWelcome: 'Hello! How can I help you with No Más Multas today?',
  helpGreeting: 'Hello! I\'m here to help you with challenging your traffic or parking tickets.',
  helpGeneral: 'I can help with uploading documents, analyzing fines, generating appeals, and more. What would you like to know?',
  helpUpload: 'To upload a document, drag and drop your file in the upload area or click to browse your files. I support PDF, JPG, and PNG formats.',
  helpAppeal: 'After uploading and analyzing your document, you can generate an appeal by selecting an appeal type and clicking the "Generate Appeal" button.',
  helpEdit: 'You can edit the fine details by clicking the "Edit" button on the Fine Details card. You can also edit the generated appeal text directly in the text area.',
  helpExport: 'You can export your appeal as a TXT or DOCX file, copy it to clipboard, or print it using the buttons at the bottom of the appeal card.',
  helpThanks: 'You\'re welcome! Feel free to ask if you need anything else.',
  helpFallback: 'I\'m not sure I understand. Could you rephrase your question? I can help with uploading documents, analyzing fines, or generating appeals.',
  helpPlaceholder: 'Type your question here...',
  openHelp: 'Open help assistant',
  closeHelp: 'Close help assistant',

  // Tour and guidance
  tourCompleted: 'Tour completed! You can now start using the app.',
  previous: 'Previous',
  next: 'Next',
  finish: 'Finish',
  tourUploadTitle: 'Upload Your Document',
  tourUploadContent: 'Start by uploading your fine document here. We support PDF, JPG, and PNG formats.',
  tourAnalyzeTitle: 'Analyze Your Document',
  tourAnalyzeContent: 'Once uploaded, click this button to analyze your document and extract fine details.',
  tourOptionsTitle: 'Configure Appeal Options',
  tourOptionsContent: 'Choose the type of appeal and customize any additional details you want to include.',
  tourGenerateTitle: 'Generate Your Appeal',
  tourGenerateContent: 'Click here to generate your appeal based on the fine details and your selected options.',
  tourAppealTitle: 'Review and Edit',
  tourAppealContent: 'Review the generated appeal and make any necessary edits before exporting or printing.',
  appealSuccessTitle: 'Appeal Generated!',
  appealSuccessMessage: 'Your appeal has been successfully generated. Now you can review and edit it before exporting.',
  helpTour: 'To start the application tour again, go to your user profile and click "Show Tour".',

  // Comparison and version control
  compareVersions: 'Compare Versions',
  originalVersion: 'Original Version',
  modifiedVersion: 'Modified Version',
  differences: 'Differences',
  close: 'Close',
  unsavedChanges: 'You have unsaved changes',
  revertChanges: 'Revert to original',

  // Voice features
  startListening: 'Start voice input',
  stopListening: 'Stop listening',
  listening: 'Listening...',
  clearChat: 'Clear chat',

  // Theme
  changeTheme: 'Change theme',
  themeLight: 'Light',
  themeDark: 'Dark',
  themeSystem: 'System',

  // Keyboard shortcuts
  keyboardShortcuts: 'Keyboard Shortcuts',
  globalShortcuts: 'Global Shortcuts',
  editorShortcuts: 'Editor Shortcuts',
  dashboardShortcuts: 'Dashboard Shortcuts',
  gotIt: 'Got it!',
  closeShortcuts: 'Close',
  'Go to Home page': 'Go to Home page',
  'Go to Dashboard': 'Go to Dashboard',
  'Create a new appeal': 'Create a new appeal',
  'View my appeals': 'View my appeals',
  'Show keyboard shortcuts help': 'Show keyboard shortcuts help',
  'Focus search': 'Focus search',
  'Close dialogs or panels': 'Close dialogs or panels',
  'Toggle language': 'Toggle language',
  'Toggle theme (dark/light)': 'Toggle theme (dark/light)',

  // PDF export
  downloadPdf: 'Download as PDF',
  generatedBy: 'Generated by',
  page: 'Page',
  of: 'of',

  // Toast notifications
  toastSuccess: 'Success',
  toastError: 'Error',
  toastInfo: 'Information',
  toastWarning: 'Warning',
  toastClose: 'Close',

  // Navigation
  dashboard: 'Dashboard',
  createAppeal: 'Create Appeal',
  myAppeals2: 'My Appeals',
  statistics: 'Statistics',
  resources: 'Resources',
  demo: 'Demo',

  // Help FAB
  getHelp: 'Get Help',
  viewGuide: 'View Guide',
  watchTutorial: 'Watch Tutorial',
  faqHelp: 'Frequently Asked Questions',
  startDemo: 'Try Demo',
}; 