'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

interface LanguageProviderProps {
  children: ReactNode;
}

type Translations = {
  [key: string]: {
    [key: string]: string;
  };
};

// Add all translations here
const translations: Translations = {
  en: {
    title: 'No Más Multas',
    subtitle: 'Challenge traffic and parking tickets with AI',
    uploadTitle: 'Upload Your Document',
    dropFiles: 'Drop files here or click to browse',
    fileType: 'Supported formats: PDF, JPG, PNG',
    detailsTitle: 'Fine Details',
    fineReference: 'Reference Number',
    fineDate: 'Date',
    fineAmount: 'Amount',
    fineLocation: 'Location',
    fineReason: 'Violation Reason',
    fineVehicle: 'Vehicle',
    editDetails: 'Edit Details',
    appealOptions: 'Appeal Options',
    appealType: 'Appeal Type',
    appealTypeProcedural: 'Procedural',
    appealTypeFactual: 'Factual',
    appealTypeLegal: 'Legal',
    appealTypeComprehensive: 'Comprehensive',
    includeTemplate: 'Include Template Text',
    customDetails: 'Custom Details (Optional)',
    customDetailsPlaceholder: 'Add any specific details you want to include in your appeal...',
    analyze: 'Analyze Document',
    generate: 'Generate Appeal',
    regenerate: 'Regenerate Appeal',
    loading: 'Processing...',
    errorOccurred: 'An error occurred. Please try again.',
    tryAgain: 'Try again or upload a different document.',
    appealResult: 'Appeal Letter',
    editableText: 'The text below is editable. Make any changes you need.',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    print: 'Print',
    download: 'Download',
    downloadTxt: 'Download as .txt',
    downloadDocx: 'Download as .docx',
    appealLetter: 'Appeal Letter',
    home: 'Home',
    about: 'About',
    howItWorks: 'How It Works',
    pricing: 'Pricing',
    contact: 'Contact',
    faq: 'FAQ',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    disclaimerTitle: 'Disclaimer',
    disclaimer: 'This tool provides assistance but does not constitute legal advice.',
    copyright: 'All rights reserved.',
    languageEn: 'English',
    languageEs: 'Spanish',
    upgrade: 'Upgrade to Premium',
    premiumFeatures: 'Get access to premium features',
    legal: 'Legal',
    cookiePolicy: 'Cookie Policy',
    quickLinks: 'Quick Links',
    appealGeneratorLabel: 'Appeal Generator',
    dashboardLabel: 'Dashboard',
    successAppealGenerated: 'Appeal generated successfully!',
    successDocumentAnalyzed: 'Document analyzed successfully!',
    
    // New translations
    characters: 'characters',
    words: 'words',
    tips: 'Writing Tips',
    tipClear: 'Be clear and concise',
    tipRespectful: 'Maintain a respectful tone',
    tipFacts: 'Focus on facts and evidence',
    tipSpecific: 'Be specific about your case',
    tipProofread: 'Proofread before submitting',
    hideDetails: 'Hide Tips',
    showDetails: 'Show Tips',
    formatBold: 'Bold',
    formatItalic: 'Italic',
    formatUnderline: 'Underline',
    formatUppercase: 'UPPERCASE',
    formatLowercase: 'lowercase',
    
    // Help Assistant
    helpAssistant: 'Help Assistant',
    helpWelcome: 'Hello! How can I help you with No Más Multas today?',
    helpGreeting: 'Hello! I\'m here to help you with challenging your traffic or parking tickets.',
    helpGeneral: 'I can help with uploading documents, analyzing fines, generating appeals, and more. What would you like to know?',
    helpUpload: 'To upload a document, drag and drop your file in the upload area or click to browse your files. I support PDF, JPG, and PNG formats.',
    helpAppeal: 'After uploading and analyzing your document, you can generate an appeal by selecting an appeal type and clicking the "Generate Appeal" button.',
    helpEdit: 'You can edit the fine details by clicking the "Edit" button on the Fine Details card. You can also edit the generated appeal text directly in the text area.',
    helpExport: 'You can export your appeal as a TXT or DOCX file, copy it to clipboard, or print it using the buttons at the bottom of the appeal card.',
    helpThanks: 'You\'re welcome! Feel free to ask if you need anything else.',
    helpFallback: 'I\'m not sure I understand. Could you rephrase your question? I can help with uploading documents, analyzing fines, or generating appeals.',
    helpPlaceholder: 'Type your question here...',
    openHelp: 'Open help assistant',
    closeHelp: 'Close help assistant',
    
    // Guided Tour translations
    tourCompleted: 'Tour completed! You can now start using the app.',
    previous: 'Previous',
    next: 'Next',
    finish: 'Finish',
    tourUploadTitle: 'Upload Your Document',
    tourUploadContent: 'Start by uploading your fine document here. We support PDF, JPG, and PNG formats.',
    tourAnalyzeTitle: 'Analyze Your Document',
    tourAnalyzeContent: 'Once uploaded, click this button to analyze your document and extract fine details.',
    tourOptionsTitle: 'Configure Appeal Options',
    tourOptionsContent: 'Choose the type of appeal and customize any additional details you want to include.',
    tourGenerateTitle: 'Generate Your Appeal',
    tourGenerateContent: 'Click here to generate your appeal based on the fine details and your selected options.',
    tourAppealTitle: 'Review and Edit',
    tourAppealContent: 'Review the generated appeal and make any necessary edits before exporting or printing.',
    
    // Celebration message
    appealSuccessTitle: 'Appeal Generated!',
    appealSuccessMessage: 'Your appeal has been successfully generated. Now you can review and edit it before exporting.',
    
    // New help assistant phrases
    helpTour: 'To start the application tour again, go to your user profile and click "Show Tour".',
    
    // Appeal comparison
    compareVersions: 'Compare Versions',
    originalVersion: 'Original Version',
    modifiedVersion: 'Modified Version',
    differences: 'Differences',
    close: 'Close',
    unsavedChanges: 'You have unsaved changes',
    revertChanges: 'Revert to original',
    
    // Chat assistant voice features
    startListening: 'Start voice input',
    stopListening: 'Stop listening',
    listening: 'Listening...',
    clearChat: 'Clear chat',
    
    // Theme translations
    changeTheme: 'Change theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    
    // Keyboard shortcuts
    keyboardShortcuts: 'Keyboard Shortcuts',
    shortcutHelp: 'Show Shortcuts',
    shortcutUpload: 'Upload Document',
    shortcutAnalyze: 'Analyze Document',
    shortcutGenerate: 'Generate Appeal',
    shortcutExport: 'Export Appeal',
    shortcutPrint: 'Print Appeal',
    shortcutCopy: 'Copy to Clipboard',
    shortcutClose: 'Close Modal',
    shortcutTip: 'Tip: Press Ctrl+? anytime to show this dialog',
    
    // PDF export
    downloadPdf: 'Download as PDF',
    generatedBy: 'Generated by',
    page: 'Page',
    of: 'of',
    
    // Appeal quality analyzer
    appealQuality: 'Appeal Quality Analysis',
    analyzing: 'Analyzing your appeal...',
    overallScore: 'Overall Score',
    clarity: 'Clarity',
    persuasiveness: 'Persuasiveness',
    professionalism: 'Professionalism',
    relevance: 'Relevance',
    confidence: 'Confidence',
    suggestions: 'Suggestions for Improvement',
    strengths: 'Strengths',
    collapse: 'Collapse',
    expand: 'Expand',
    scoreExcellent: 'Excellent',
    scoreVeryGood: 'Very Good',
    scoreGood: 'Good',
    scoreFair: 'Fair',
    scoreNeedsWork: 'Needs Work',
    scorePoor: 'Poor',
    analyzeAppeal: 'Analyze Appeal Quality',
    suggestFormatting: 'Use shorter sentences and break text into more paragraphs for better clarity.',
    suggestPersuasive: 'Include more specific evidence and causal reasoning (using words like "because" and "therefore").',
    suggestFormal: 'Use a more formal tone appropriate for legal communication.',
    suggestClosing: 'Add a formal closing like "Sincerely" or "Respectfully" at the end of your appeal.',
    suggestProcedural: 'Focus more on the procedural errors, like notice issues, timeframes, or delivery methods.',
    suggestFactual: 'Include more specific facts about what happened in your appeal.',
    suggestEvidence: 'Reference specific evidence like photos, dates, or witness information.',
    suggestLegal: 'Cite relevant laws, codes, or regulations to strengthen your legal argument.',
    suggestComprehensive: 'Include a mix of procedural, factual, and legal arguments for a more comprehensive appeal.',
    suggestMoreDetail: 'Your appeal is quite short. Adding more details would make it more persuasive.',
    suggestConfidence: 'Use more assertive language and active voice to sound more confident.',
    strengthClarity: 'Your appeal is easy to read and understand.',
    strengthPersuasive: 'You use effective persuasive language and reasoning.',
    strengthProfessional: 'Your appeal maintains a professional tone appropriate for legal communication.',
    strengthProcedural: 'You effectively highlight procedural issues with the citation.',
    strengthFactual: 'Your presentation of the facts is clear and compelling.',
    strengthLegal: 'Your legal references strengthen your argument.',
    strengthComprehensive: 'You effectively combine multiple types of arguments.',
    strengthConfidence: 'Your appeal sounds confident and authoritative.',
    textIssues: 'Specific Text Issues',
    showTextAnalysis: 'Show Issues',
    hideTextAnalysis: 'Hide Issues',
    generalIssue: 'General Issue',
    longSentenceWarning: 'This sentence is very long and may be difficult to understand.',
    passiveVoiceSuggestion: 'Passive voice detected. Active voice is generally more persuasive.',
    weakPhraseSuggestion: 'This phrase weakens your argument.',
    missingLegalReferences: 'Your legal appeal lacks specific legal references.',
    missingEvidenceReference: 'Your factual appeal could be strengthened with specific evidence references.',
    applySuggestion: 'Apply',
    
    // Templates Library
    templatesLibrary: 'Templates Library',
    saveAsTemplate: 'Save as Template',
    templateName: 'Template Name',
    templateDescription: 'Template Description',
    templateCategory: 'Category',
    templateTags: 'Tags',
    templateSaved: 'Template saved successfully',
    templateDeleted: 'Template deleted',
    templateApplied: 'Template applied',
    myTemplates: 'My Templates',
    publicTemplates: 'Public Templates',
    searchTemplates: 'Search templates...',
    applyTemplate: 'Apply Template',
    editTemplate: 'Edit Template',
    deleteTemplate: 'Delete Template',
    confirmDeleteTemplate: 'Are you sure you want to delete this template?',
    templateSuccess: 'Success rate:',
    
    // Categories
    categoryProcedural: 'Procedural Appeals',
    categoryFactual: 'Factual Appeals',
    categoryLegal: 'Legal Appeals',
    categoryComprehensive: 'Comprehensive Appeals',
    categoryParking: 'Parking Tickets',
    categorySpeed: 'Speed Tickets',
    categoryRedLight: 'Red Light Tickets',
    categoryOther: 'Other',
    
    // Appeal Stats
    appealStatsTitle: 'Appeal Success Statistics',
    statsOverview: 'Overview',
    statsByType: 'By Appeal Type',
    statsByReason: 'By Violation Type',
    statsTotal: 'Total Appeals',
    statsSuccessful: 'Successful Appeals',
    statsPending: 'Pending Appeals',
    statsRejected: 'Rejected Appeals',
    statsAvgResponse: 'Avg. Response Time',
    statsDays: 'days',
    statsMostSuccessful: 'Most Successful Arguments',
    statsStatus: 'Appeal Status Breakdown',
    statsSuccess: 'Success Rate',
    
    // Legal Argument Generator
    legalArgumentsTitle: 'Legal Arguments Generator',
    useThisArgument: 'Use This Argument',
    argumentSelected: 'Argument Selected',
    noArgumentsFound: 'No legal arguments found for this violation type',
    successRate: 'Success Rate',
    legalReference: 'Legal Reference',
    precedentCase: 'Precedent Case',
    
    // Violation types for legal arguments
    violationTypeParking: 'Parking Violation',
    violationTypeSpeed: 'Speeding Violation',
    violationTypeRedLight: 'Red Light Violation',
    violationTypeOther: 'Other Violation',
    
    // Dashboard
    dashboardTitle: 'Dashboard',
    recentAppeals: 'Recent Appeals',
    pendingAppeals: 'Pending Appeals',
    completedAppeals: 'Completed Appeals',
    viewAll: 'View All',
    noRecentActivity: 'No recent activity',
    
    // User profile
    profileSettings: 'Profile Settings',
    accountInfo: 'Account Information',
    notificationSettings: 'Notification Settings',
    emailNotifications: 'Email Notifications',
    privacySettings: 'Privacy Settings',
    
    // RegulationFinder translations
    regulationFinderTitle: 'Traffic Regulation Finder',
    regulationFinderDescription: 'Search for traffic and parking regulations relevant to your case. Add specific regulations to strengthen your appeal.',
    searchQuery: 'Search',
    searchRegulationsPlaceholder: 'Search by keyword or code...',
    jurisdiction: 'Jurisdiction',
    allJurisdictions: 'All Jurisdictions',
    violationType: 'Violation Type',
    allViolationTypes: 'All Violation Types',
    results: 'Results',
    searching: 'Searching...',
    errorFetchingRegulations: 'Failed to fetch regulations. Please try again later.',
    noRegulationsFound: 'No regulations found',
    tryDifferentSearch: 'Try a different search term or filter',
    useRegulation: 'Use this regulation',
    regulationSelected: 'Selected',
    fullText: 'Full Text',
    source: 'Source',
    expandDetails: 'Expand details',
    collapseDetails: 'Collapse details',
    viewSource: 'View source',
    
    // Jurisdictions
    jurisdictionCalifornia: 'California',
    jurisdictionNewYork: 'New York',
    jurisdictionTexas: 'Texas',
    jurisdictionFlorida: 'Florida',
    jurisdictionIllinois: 'Illinois',
    jurisdictionPennsylvania: 'Pennsylvania',
    jurisdictionFederal: 'Federal',
    
    // Violation types (for RegulationFinder)
    violationTypeParking2: 'Parking',
    violationTypeSpeeding2: 'Speeding',
    violationTypeRedLight2: 'Red Light',
    violationTypeStopSign2: 'Stop Sign',
    violationTypeRightOfWay2: 'Right of Way',
    violationTypeRegistration2: 'Vehicle Registration',
    violationTypeLicense2: 'Driver License',
    violationTypeInsurance2: 'Insurance',
    violationTypeOther2: 'Other',
    
    // Appeal Text component buttons
    showRegulations: 'Find Regulations',
    hideRegulations: 'Hide Regulations',
    
    // Appeal Status Tracker translations
    appealStatus: 'Appeal Status',
    lastUpdated: 'Last updated',
    refresh: 'Refresh',
    currentStatus: 'Current Status',
    estimatedResponse: 'Estimated Response',
    authority: 'Authority',
    appealProgress: 'Appeal Progress',
    submitted: 'Submitted',
    received: 'Received',
    under_review: 'Under Review',
    decision_pending: 'Decision Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    latestNotes: 'Latest Notes',
    noNotesAvailable: 'No notes available at this time',
    trackingNumber: 'Tracking Number',
    copyToClipboard: 'Copy to clipboard',
    appealSubmitted: 'Appeal submitted successfully',
    appealReceived: 'Appeal received by authorities',
    appealUnderReview: 'Appeal is being reviewed',
    decisionPending: 'Decision is being finalized',
    appealCompleted: 'Appeal process completed',
    appealRejected: 'Appeal was rejected',
    referenceNumber: 'Reference Number',
    currentStep: 'Current Step',
    day: 'day',
    days: 'days',
    hour: 'hour',
    hours: 'hours',
    minute: 'minute',
    minutes: 'minutes',
    ago: 'ago',
    whatNext: 'What happens next?',
    afterSubmissionInfo: 'Your appeal has been submitted and is awaiting receipt confirmation. This typically takes 1-2 business days.',
    afterReceiptInfo: 'Your appeal has been received and is in the queue for review. The review process typically begins within 3-5 business days.',
    duringReviewInfo: 'Your appeal is currently being reviewed by an officer. This process typically takes 5-10 business days to complete.',
    pendingDecisionInfo: 'Your appeal has been reviewed and a decision is being finalized. You should receive the final decision within 3-5 business days.',
    afterCompletionInfo: 'Your appeal process has been completed. You should have received the final decision. If you disagree with the outcome, you may have options for further appeal.',
    afterRejectionInfo: 'Your appeal has been rejected. You should have received details about the rejection reason. You may have options for a secondary appeal depending on your jurisdiction.',
    errorFetchingStatus: 'Failed to fetch appeal status. Please try again later.',
    errorOccurred2: 'An error occurred',
    tryAgain2: 'Try Again',
    refreshEvery30Seconds: 'Refresh every 30 seconds',
    refreshEveryMinute: 'Refresh every minute',
    refreshEvery5Minutes: 'Refresh every 5 minutes',
    refreshEvery10Minutes: 'Refresh every 10 minutes',
    
    // Appeal List and Details Page translations
    myAppeals: 'My Appeals',
    createNewAppeal: 'Create New Appeal',
    allAppeals: 'All Appeals',
    activeAppeals: 'Active Appeals',
    completedAppeals2: 'Completed',
    rejectedAppeals: 'Rejected',
    sortBy: 'Sort by:',
    submissionDate: 'Submission Date',
    status: 'Status',
    appealType2: 'Appeal Type',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    noAppealsFound: 'No appeals found',
    createAppealToGetStarted: 'Create an appeal to get started',
    violationReason: 'Violation',
    fineAmount2: 'Fine',
    errorFetchingAppeals: 'Failed to fetch appeals. Please try again later.',
    
    // Appeal Details Page
    backToAppeals: 'Back to My Appeals',
    submittedOn: 'Submitted on',
    fineDetails: 'Fine Details',
    fineNumber: 'Fine Number',
    fineDate2: 'Date of Fine',
    fineReason2: 'Reason',
    fineLocation2: 'Location',
    officerName: 'Officer Name',
    appealContent: 'Appeal Content',
    actions: 'Actions',
    editAppeal: 'Edit Appeal',
    printAppeal: 'Print Appeal',
    downloadPDF: 'Download PDF',
    fileReappeal: 'File a Re-Appeal',
    appealNotFound: 'Appeal not found',
    errorFetchingAppealDetails: 'Failed to fetch appeal details',
    
    // Demo page
    appealWritingAssistant: 'Appeal Writing Assistant',
    appealEditor: 'Appeal Editor',
    demoExplanation: 'Write your appeal below and get real-time quality analysis and suggestions. The analyzer will automatically evaluate your text and provide actionable feedback.',
    demoTip: 'Try writing a sample appeal then click "Analyze" in the toolbar to see real-time quality analysis. Apply suggested changes and see your score improve!',
    howToUse: 'How to Use the Appeal Quality Analyzer',
    tipBullet1: 'Click "Analyze" in the toolbar to analyze your appeal',
    tipBullet2: 'Review the overall score and individual metrics like clarity, persuasiveness, etc.',
    tipBullet3: 'Click "Show Issues" to see specific text problems with suggested corrections',
    tipBullet4: 'Click "Apply" on any suggestion to automatically apply the correction',
    tipBullet5: 'Implement the suggestions to improve your appeal quality',
    tipBullet6: 'Analyze again to see your improved score',
    demoNote: 'This is a demo of the appeal quality analyzer. In a real application, this component would be integrated throughout the appeal writing process to provide continuous feedback.',
    
    // Navigation
    dashboard: 'Dashboard',
    createAppeal: 'Create Appeal',
    myAppeals2: 'My Appeals',
    statistics: 'Statistics',
    resources: 'Resources',
    demo: 'Demo',
  },
  es: {
    title: 'No Más Multas',
    subtitle: 'Impugna multas de tráfico y estacionamiento con IA',
    uploadTitle: 'Sube tu documento',
    dropFiles: 'Suelta archivos aquí o haz clic para explorar',
    fileType: 'Formatos compatibles: PDF, JPG, PNG',
    detailsTitle: 'Detalles de la multa',
    fineReference: 'Número de referencia',
    fineDate: 'Fecha',
    fineAmount: 'Importe',
    fineLocation: 'Ubicación',
    fineReason: 'Motivo de la infracción',
    fineVehicle: 'Vehículo',
    editDetails: 'Editar detalles',
    appealOptions: 'Opciones de recurso',
    appealType: 'Tipo de recurso',
    appealTypeProcedural: 'Procesal',
    appealTypeFactual: 'Factual',
    appealTypeLegal: 'Legal',
    appealTypeComprehensive: 'Completo',
    includeTemplate: 'Incluir texto de plantilla',
    customDetails: 'Detalles personalizados (Opcional)',
    customDetailsPlaceholder: 'Añade cualquier detalle específico que quieras incluir en tu recurso...',
    analyze: 'Analizar documento',
    generate: 'Generar recurso',
    regenerate: 'Regenerar recurso',
    loading: 'Procesando...',
    errorOccurred: 'Ha ocurrido un error. Por favor, inténtalo de nuevo.',
    tryAgain: 'Inténtalo de nuevo o sube un documento diferente.',
    appealResult: 'Carta de recurso',
    editableText: 'El texto a continuación es editable. Realiza los cambios que necesites.',
    copy: 'Copiar',
    copied: '¡Copiado!',
    export: 'Exportar',
    print: 'Imprimir',
    download: 'Descargar',
    downloadTxt: 'Descargar como .txt',
    downloadDocx: 'Descargar como .docx',
    appealLetter: 'Carta de recurso',
    home: 'Inicio',
    about: 'Acerca de',
    howItWorks: 'Cómo funciona',
    pricing: 'Precios',
    contact: 'Contacto',
    faq: 'Preguntas frecuentes',
    termsOfService: 'Términos de servicio',
    privacyPolicy: 'Política de privacidad',
    disclaimerTitle: 'Aviso legal',
    disclaimer: 'Esta herramienta proporciona asistencia pero no constituye asesoramiento legal.',
    copyright: 'Todos los derechos reservados.',
    languageEn: 'Inglés',
    languageEs: 'Español',
    upgrade: 'Actualizar a Premium',
    premiumFeatures: 'Obtén acceso a funciones premium',
    legal: 'Legal',
    cookiePolicy: 'Política de cookies',
    quickLinks: 'Enlaces rápidos',
    appealGeneratorLabel: 'Generador de recursos',
    dashboardLabel: 'Panel de control',
    successAppealGenerated: '¡Recurso generado con éxito!',
    successDocumentAnalyzed: '¡Documento analizado con éxito!',
    
    // New translations
    characters: 'caracteres',
    words: 'palabras',
    tips: 'Consejos de redacción',
    tipClear: 'Sé claro y conciso',
    tipRespectful: 'Mantén un tono respetuoso',
    tipFacts: 'Céntrate en hechos y pruebas',
    tipSpecific: 'Sé específico sobre tu caso',
    tipProofread: 'Revisa antes de enviar',
    hideDetails: 'Ocultar consejos',
    showDetails: 'Mostrar consejos',
    formatBold: 'Negrita',
    formatItalic: 'Cursiva',
    formatUnderline: 'Subrayado',
    formatUppercase: 'MAYÚSCULAS',
    formatLowercase: 'minúsculas',
    
    // Help Assistant
    helpAssistant: 'Asistente de ayuda',
    helpWelcome: '¡Hola! ¿Cómo puedo ayudarte con No Más Multas hoy?',
    helpGreeting: '¡Hola! Estoy aquí para ayudarte a impugnar tus multas de tráfico o estacionamiento.',
    helpGeneral: 'Puedo ayudarte a subir documentos, analizar multas, generar recursos y más. ¿Qué te gustaría saber?',
    helpUpload: 'Para subir un documento, arrastra y suelta tu archivo en el área de carga o haz clic para explorar tus archivos. Compatible con formatos PDF, JPG y PNG.',
    helpAppeal: 'Después de cargar y analizar tu documento, puedes generar un recurso seleccionando un tipo de recurso y haciendo clic en el botón "Generar recurso".',
    helpEdit: 'Puedes editar los detalles de la multa haciendo clic en el botón "Editar" en la tarjeta de Detalles de la multa. También puedes editar el texto del recurso generado directamente en el área de texto.',
    helpExport: 'Puedes exportar tu recurso como un archivo TXT o DOCX, copiarlo al portapapeles o imprimirlo usando los botones en la parte inferior de la tarjeta de recurso.',
    helpThanks: '¡De nada! No dudes en preguntar si necesitas algo más.',
    helpFallback: 'No estoy seguro de entender. ¿Podrías reformular tu pregunta? Puedo ayudarte con la carga de documentos, el análisis de multas o la generación de recursos.',
    helpPlaceholder: 'Escribe tu pregunta aquí...',
    openHelp: 'Abrir asistente de ayuda',
    closeHelp: 'Cerrar asistente de ayuda',
    
    // Guided Tour translations
    tourCompleted: '¡Recorrido completado! Ahora puedes comenzar a usar la aplicación.',
    previous: 'Anterior',
    next: 'Siguiente',
    finish: 'Finalizar',
    tourUploadTitle: 'Sube tu documento',
    tourUploadContent: 'Comienza subiendo tu documento de multa aquí. Admitimos formatos PDF, JPG y PNG.',
    tourAnalyzeTitle: 'Analiza tu documento',
    tourAnalyzeContent: 'Una vez subido, haz clic en este botón para analizar tu documento y extraer los detalles de la multa.',
    tourOptionsTitle: 'Configura las opciones de recurso',
    tourOptionsContent: 'Elige el tipo de recurso y personaliza cualquier detalle adicional que quieras incluir.',
    tourGenerateTitle: 'Genera tu recurso',
    tourGenerateContent: 'Haz clic aquí para generar tu recurso basado en los detalles de la multa y las opciones seleccionadas.',
    tourAppealTitle: 'Revisa y edita',
    tourAppealContent: 'Revisa el recurso generado y realiza las ediciones necesarias antes de exportarlo o imprimirlo.',
    
    // Celebration message
    appealSuccessTitle: '¡Recurso generado!',
    appealSuccessMessage: 'Tu recurso ha sido generado con éxito. Ahora puedes revisarlo y editarlo antes de exportarlo.',
    
    // New help assistant phrases
    helpTour: 'Para iniciar el recorrido de la aplicación de nuevo, ve a tu perfil de usuario y haz clic en "Mostrar recorrido".',
    
    // Appeal comparison
    compareVersions: 'Comparar Versiones',
    originalVersion: 'Versión Original',
    modifiedVersion: 'Versión Modificada',
    differences: 'Diferencias',
    close: 'Cerrar',
    unsavedChanges: 'Tienes cambios sin guardar',
    revertChanges: 'Volver al original',
    
    // Chat assistant voice features
    startListening: 'Iniciar entrada de voz',
    stopListening: 'Detener escucha',
    listening: 'Escuchando...',
    clearChat: 'Limpiar chat',
    
    // Theme translations
    changeTheme: 'Cambiar tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Sistema',
    
    // Keyboard shortcuts
    keyboardShortcuts: 'Atajos de Teclado',
    shortcutHelp: 'Mostrar Atajos',
    shortcutUpload: 'Subir Documento',
    shortcutAnalyze: 'Analizar Documento',
    shortcutGenerate: 'Generar Recurso',
    shortcutExport: 'Exportar Recurso',
    shortcutPrint: 'Imprimir Recurso',
    shortcutCopy: 'Copiar al Portapapeles',
    shortcutClose: 'Cerrar Ventana',
    shortcutTip: 'Consejo: Pulsa Ctrl+? en cualquier momento para mostrar este diálogo',
    
    // PDF export
    downloadPdf: 'Descargar como PDF',
    generatedBy: 'Generado por',
    page: 'Página',
    of: 'de',
    
    // Appeal quality analyzer
    appealQuality: 'Análisis de Calidad del Recurso',
    analyzing: 'Analizando tu recurso...',
    overallScore: 'Puntuación General',
    clarity: 'Claridad',
    persuasiveness: 'Persuasión',
    professionalism: 'Profesionalismo',
    relevance: 'Relevancia',
    confidence: 'Confianza',
    suggestions: 'Sugerencias para Mejorar',
    strengths: 'Puntos Fuertes',
    collapse: 'Colapsar',
    expand: 'Expandir',
    scoreExcellent: 'Excelente',
    scoreVeryGood: 'Muy Bueno',
    scoreGood: 'Bueno',
    scoreFair: 'Aceptable',
    scoreNeedsWork: 'Necesita Mejoras',
    scorePoor: 'Insuficiente',
    analyzeAppeal: 'Analizar Calidad del Recurso',
    suggestFormatting: 'Usa frases más cortas y divide el texto en más párrafos para mayor claridad.',
    suggestPersuasive: 'Incluye más evidencia específica y razonamiento causal (usando palabras como "porque" y "por lo tanto").',
    suggestFormal: 'Utiliza un tono más formal apropiado para comunicaciones legales.',
    suggestClosing: 'Añade un cierre formal como "Atentamente" o "Respetuosamente" al final de tu recurso.',
    suggestProcedural: 'Enfócate más en los errores procedimentales, como problemas de notificación, plazos o métodos de entrega.',
    suggestFactual: 'Incluye más hechos específicos sobre lo que ocurrió en tu recurso.',
    suggestEvidence: 'Haz referencia a evidencia específica como fotos, fechas o información de testigos.',
    suggestLegal: 'Cita leyes, códigos o regulaciones relevantes para fortalecer tu argumento legal.',
    suggestComprehensive: 'Incluye una mezcla de argumentos procedimentales, factuales y legales para un recurso más completo.',
    suggestMoreDetail: 'Tu recurso es bastante corto. Añadir más detalles lo haría más persuasivo.',
    suggestConfidence: 'Utiliza un lenguaje más asertivo y voz activa para sonar más seguro.',
    strengthClarity: 'Tu recurso es fácil de leer y entender.',
    strengthPersuasive: 'Utilizas un lenguaje persuasivo y razonamiento efectivo.',
    strengthProfessional: 'Tu recurso mantiene un tono profesional apropiado para comunicaciones legales.',
    strengthProcedural: 'Destacas eficazmente los problemas procedimentales de la multa.',
    strengthFactual: 'Tu presentación de los hechos es clara y convincente.',
    strengthLegal: 'Tus referencias legales refuerzan tu argumento.',
    strengthComprehensive: 'Combinas eficazmente múltiples tipos de argumentos.',
    strengthConfidence: 'Tu recurso suena seguro y con autoridad.',
    textIssues: 'Problemas Específicos del Texto',
    showTextAnalysis: 'Mostrar Problemas',
    hideTextAnalysis: 'Ocultar Problemas',
    generalIssue: 'Problema General',
    longSentenceWarning: 'Esta frase es muy larga y puede ser difícil de entender.',
    passiveVoiceSuggestion: 'Voz pasiva detectada. La voz activa es generalmente más persuasiva.',
    weakPhraseSuggestion: 'Esta frase debilita tu argumento.',
    missingLegalReferences: 'Tu recurso legal carece de referencias legales específicas.',
    missingEvidenceReference: 'Tu recurso factual podría fortalecerse con referencias específicas a evidencias.',
    applySuggestion: 'Aplicar',
    
    // Templates Library
    templatesLibrary: 'Biblioteca de Plantillas',
    saveAsTemplate: 'Guardar como Plantilla',
    templateName: 'Nombre de Plantilla',
    templateDescription: 'Descripción de Plantilla',
    templateCategory: 'Categoría',
    templateTags: 'Etiquetas',
    templateSaved: 'Plantilla guardada exitosamente',
    templateDeleted: 'Plantilla eliminada',
    templateApplied: 'Plantilla aplicada',
    myTemplates: 'Mis Plantillas',
    publicTemplates: 'Plantillas Públicas',
    searchTemplates: 'Buscar plantillas...',
    applyTemplate: 'Aplicar Plantilla',
    editTemplate: 'Editar Plantilla',
    deleteTemplate: 'Eliminar Plantilla',
    confirmDeleteTemplate: '¿Estás seguro que deseas eliminar esta plantilla?',
    templateSuccess: 'Tasa de éxito:',
    
    // Categories
    categoryProcedural: 'Recursos Procedimentales',
    categoryFactual: 'Recursos Factuales',
    categoryLegal: 'Recursos Legales',
    categoryComprehensive: 'Recursos Integrales',
    categoryParking: 'Multas de Estacionamiento',
    categorySpeed: 'Multas de Velocidad',
    categoryRedLight: 'Multas de Semáforo en Rojo',
    categoryOther: 'Otros',
    
    // Appeal Stats
    appealStatsTitle: 'Estadísticas de Éxito de Recursos',
    statsOverview: 'Visión General',
    statsByType: 'Por Tipo de Recurso',
    statsByReason: 'Por Tipo de Infracción',
    statsTotal: 'Total de Recursos',
    statsSuccessful: 'Recursos Exitosos',
    statsPending: 'Recursos Pendientes',
    statsRejected: 'Recursos Rechazados',
    statsAvgResponse: 'Tiempo Promedio de Respuesta',
    statsDays: 'días',
    statsMostSuccessful: 'Argumentos Más Exitosos',
    statsStatus: 'Desglose de Estado de Recursos',
    statsSuccess: 'Tasa de Éxito',
    
    // Legal Argument Generator
    legalArgumentsTitle: 'Generador de Argumentos Legales',
    useThisArgument: 'Usar Este Argumento',
    argumentSelected: 'Argumento Seleccionado',
    noArgumentsFound: 'No se encontraron argumentos legales para este tipo de infracción',
    successRate: 'Tasa de Éxito',
    legalReference: 'Referencia Legal',
    precedentCase: 'Caso Precedente',
    
    // Violation types for legal arguments
    violationTypeParking: 'Infracción de Estacionamiento',
    violationTypeSpeed: 'Infracción por Exceso de Velocidad',
    violationTypeRedLight: 'Infracción de Semáforo en Rojo',
    violationTypeOther: 'Otra Infracción',
    
    // Dashboard
    dashboardTitle: 'Panel de Control',
    recentAppeals: 'Recursos Recientes',
    pendingAppeals: 'Recursos Pendientes',
    completedAppeals: 'Recursos Completados',
    viewAll: 'Ver Todos',
    noRecentActivity: 'Sin actividad reciente',
    
    // User profile
    profileSettings: 'Configuración del Perfil',
    accountInfo: 'Información de la Cuenta',
    notificationSettings: 'Configuración de Notificaciones',
    emailNotifications: 'Notificaciones por Correo Electrónico',
    privacySettings: 'Configuración de Privacidad',
    
    // RegulationFinder translations
    regulationFinderTitle: 'Buscador de Regulaciones de Tráfico',
    regulationFinderDescription: 'Busca regulaciones de tráfico y estacionamiento relevantes para tu caso. Agrega regulaciones específicas para fortalecer tu recurso.',
    searchQuery: 'Buscar',
    searchRegulationsPlaceholder: 'Buscar por palabra clave o código...',
    jurisdiction: 'Jurisdicción',
    allJurisdictions: 'Todas las Jurisdicciones',
    violationType: 'Tipo de Infracción',
    allViolationTypes: 'Todos los Tipos de Infracción',
    results: 'Resultados',
    searching: 'Buscando...',
    errorFetchingRegulations: 'Error al obtener regulaciones. Por favor, inténtalo más tarde.',
    noRegulationsFound: 'No se encontraron regulaciones',
    tryDifferentSearch: 'Intenta con otros términos o filtros de búsqueda',
    useRegulation: 'Usar esta regulación',
    regulationSelected: 'Seleccionada',
    fullText: 'Texto Completo',
    source: 'Fuente',
    expandDetails: 'Expandir detalles',
    collapseDetails: 'Contraer detalles',
    viewSource: 'Ver fuente',
    
    // Jurisdictions
    jurisdictionCalifornia: 'California',
    jurisdictionNewYork: 'Nueva York',
    jurisdictionTexas: 'Texas',
    jurisdictionFlorida: 'Florida',
    jurisdictionIllinois: 'Illinois',
    jurisdictionPennsylvania: 'Pensilvania',
    jurisdictionFederal: 'Federal',
    
    // Violation types (for RegulationFinder)
    violationTypeParking2: 'Estacionamiento',
    violationTypeSpeeding2: 'Exceso de velocidad',
    violationTypeRedLight2: 'Semáforo en rojo',
    violationTypeStopSign2: 'Señal de alto',
    violationTypeRightOfWay2: 'Derecho de paso',
    violationTypeRegistration2: 'Registro de vehículo',
    violationTypeLicense2: 'Licencia de conducir',
    violationTypeInsurance2: 'Seguro',
    violationTypeOther2: 'Otro',
    
    // Appeal Text component buttons
    showRegulations: 'Buscar Regulaciones',
    hideRegulations: 'Ocultar Regulaciones',
    
    // Appeal Status Tracker translations
    appealStatus: 'Estado del Recurso',
    lastUpdated: 'Última actualización',
    refresh: 'Actualizar',
    currentStatus: 'Estado Actual',
    estimatedResponse: 'Respuesta Estimada',
    authority: 'Autoridad',
    appealProgress: 'Progreso del Recurso',
    submitted: 'Enviado',
    received: 'Recibido',
    under_review: 'En Revisión',
    decision_pending: 'Decisión Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    latestNotes: 'Últimas Notas',
    noNotesAvailable: 'No hay notas disponibles en este momento',
    trackingNumber: 'Número de Seguimiento',
    copyToClipboard: 'Copiar al portapapeles',
    appealSubmitted: 'Recurso enviado exitosamente',
    appealReceived: 'Recurso recibido por las autoridades',
    appealUnderReview: 'El recurso está siendo revisado',
    decisionPending: 'La decisión está siendo finalizada',
    appealCompleted: 'Proceso de recurso completado',
    appealRejected: 'El recurso fue rechazado',
    referenceNumber: 'Número de Referencia',
    currentStep: 'Paso Actual',
    day: 'día',
    days: 'días',
    hour: 'hora',
    hours: 'horas',
    minute: 'minuto',
    minutes: 'minutos',
    ago: 'atrás',
    whatNext: '¿Qué sigue?',
    afterSubmissionInfo: 'Tu recurso ha sido enviado y está esperando confirmación de recepción. Esto generalmente toma 1-2 días hábiles.',
    afterReceiptInfo: 'Tu recurso ha sido recibido y está en la cola para revisión. El proceso de revisión generalmente comienza dentro de 3-5 días hábiles.',
    duringReviewInfo: 'Tu recurso está siendo revisado actualmente por un oficial. Este proceso generalmente toma 5-10 días hábiles para completarse.',
    pendingDecisionInfo: 'Tu recurso ha sido revisado y se está finalizando una decisión. Deberías recibir la decisión final dentro de 3-5 días hábiles.',
    afterCompletionInfo: 'Tu proceso de recurso ha sido completado. Deberías haber recibido la decisión final. Si no estás de acuerdo con el resultado, puedes tener opciones para un recurso adicional.',
    afterRejectionInfo: 'Tu recurso ha sido rechazado. Deberías haber recibido detalles sobre el motivo del rechazo. Es posible que tengas opciones para un recurso secundario según tu jurisdicción.',
    errorFetchingStatus: 'Error al obtener el estado del recurso. Por favor, inténtalo de nuevo más tarde.',
    errorOccurred2: 'Ocurrió un error',
    tryAgain2: 'Intentar de nuevo',
    refreshEvery30Seconds: 'Actualizar cada 30 segundos',
    refreshEveryMinute: 'Actualizar cada minuto',
    refreshEvery5Minutes: 'Actualizar cada 5 minutos',
    refreshEvery10Minutes: 'Actualizar cada 10 minutos',
    
    // Appeal List and Details Page translations
    myAppeals: 'Mis Recursos',
    createNewAppeal: 'Crear Nuevo Recurso',
    allAppeals: 'Todos los Recursos',
    activeAppeals: 'Recursos Activos',
    completedAppeals2: 'Completados',
    rejectedAppeals: 'Rechazados',
    sortBy: 'Ordenar por:',
    submissionDate: 'Fecha de Envío',
    status: 'Estado',
    appealType2: 'Tipo de Recurso',
    sortAscending: 'Ordenar ascendente',
    sortDescending: 'Ordenar descendente',
    noAppealsFound: 'No se encontraron recursos',
    createAppealToGetStarted: 'Crea un recurso para comenzar',
    violationReason: 'Infracción',
    fineAmount2: 'Multa',
    errorFetchingAppeals: 'Error al obtener recursos. Por favor, inténtalo más tarde.',
    
    // Appeal Details Page
    backToAppeals: 'Volver a Mis Recursos',
    submittedOn: 'Enviado el',
    fineDetails: 'Detalles de la Multa',
    fineNumber: 'Número de Multa',
    fineDate2: 'Fecha de la Multa',
    fineReason2: 'Motivo',
    fineLocation2: 'Ubicación',
    officerName: 'Nombre del Oficial',
    appealContent: 'Contenido del Recurso',
    actions: 'Acciones',
    editAppeal: 'Editar Recurso',
    printAppeal: 'Imprimir Recurso',
    downloadPDF: 'Descargar PDF',
    fileReappeal: 'Presentar un Nuevo Recurso',
    appealNotFound: 'Recurso no encontrado',
    errorFetchingAppealDetails: 'Error al obtener detalles del recurso',
    
    // Demo page
    appealWritingAssistant: 'Asistente de Escritura de Recursos',
    appealEditor: 'Editor de Recursos',
    demoExplanation: 'Escribe tu recurso a continuación y obtén análisis de calidad y sugerencias en tiempo real. El analizador evaluará automáticamente tu texto y proporcionará comentarios procesables.',
    demoTip: '¡Intenta escribir un recurso de ejemplo y luego haz clic en "Analizar" en la barra de herramientas para ver el análisis de calidad en tiempo real. ¡Aplica los cambios sugeridos y observa cómo mejora tu puntuación!',
    howToUse: 'Cómo Usar el Analizador de Calidad de Recursos',
    tipBullet1: 'Haz clic en "Analizar" en la barra de herramientas para analizar tu recurso',
    tipBullet2: 'Revisa la puntuación general y las métricas individuales como claridad, persuasión, etc.',
    tipBullet3: 'Haz clic en "Mostrar Problemas" para ver problemas específicos del texto con correcciones sugeridas',
    tipBullet4: 'Haz clic en "Aplicar" en cualquier sugerencia para aplicar automáticamente la corrección',
    tipBullet5: 'Implementa las sugerencias para mejorar la calidad de tu recurso',
    tipBullet6: 'Analiza de nuevo para ver tu puntuación mejorada',
    demoNote: 'Esto es una demostración del analizador de calidad de recursos. En una aplicación real, este componente estaría integrado a lo largo del proceso de escritura del recurso para proporcionar retroalimentación continua.',
    
    // Navigation
    dashboard: 'Panel',
    createAppeal: 'Crear Recurso',
    myAppeals2: 'Mis Recursos',
    statistics: 'Estadísticas',
    resources: 'Recursos',
    demo: 'Demo',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations.en): string => {
    const translation = translations[language][key] || key;
    return String(translation);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
} 